package PythonMPS.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface IModule_BehaviorDescriptor extends IQNamedConcept_BehaviorDescriptor {
  public List<SNode> virtual_contents_5549669319191147593(SNode thisNode);
  public List<SNode> virtual_subModules_5549669319191147617(SNode thisNode);
}
