package PythonMPS.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ImportedValue_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IModuleContent_BehaviorDescriptor, IQNamedConcept_BehaviorDescriptor {
  public SNode virtual_container_5549669319191144388(SNode __thisNode__) {
    return null;
  }
  public String virtual_getFqName_1213877404258(SNode __thisNode__) {
    return null;
  }
  public String virtual_qualifiedName_5549669319191144399(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "PythonMPS.structure.ImportedValue";
  }

}
