package PythonMPS.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class ImportedModule_Behavior {
  public static void call_importContentsAndSubModules_5549669319190172829(SNode __thisNode__) {
    ImportedModule__BehaviorDescriptor.importContentsAndSubModules_id4O4oHuBdHit(__thisNode__);
  }
  public static int call_nbOfLevel_5549669319190682782(SNode __thisNode__) {
    return ImportedModule__BehaviorDescriptor.nbOfLevel_id4O4oHuBfDMu(__thisNode__);
  }
  public static SNode call_getSubmoduleBySimpleName_5549669319190717547(SNode __thisNode__, String name) {
    return ImportedModule__BehaviorDescriptor.getSubmoduleBySimpleName_id4O4oHuBfMhF(__thisNode__, name);
  }
  public static SNode call_getSubmoduleByQname_5549669319190908667(SNode __thisNode__, String qname) {
    return ImportedModule__BehaviorDescriptor.getSubmoduleByQname_id4O4oHuBgwVV(__thisNode__, qname);
  }
  public static SNode call_getOrCreateSubmoduleByQname_5549669319190714480(SNode __thisNode__, String name) {
    return ImportedModule__BehaviorDescriptor.getOrCreateSubmoduleByQname_id4O4oHuBfLxK(__thisNode__, name);
  }
  public static SNode call_getOrCreateSubmoduleBySimpleName_5549669319191072069(SNode __thisNode__, String name) {
    return ImportedModule__BehaviorDescriptor.getOrCreateSubmoduleBySimpleName_id4O4oHuBh8P5(__thisNode__, name);
  }
  public static void call_createSubmoduleByQname_5549669319190670441(SNode __thisNode__, String qname) {
    ImportedModule__BehaviorDescriptor.createSubmoduleByQname_id4O4oHuBfALD(__thisNode__, qname);
  }
  public static void call_createSubmoduleBySimpleName_5549669319190886061(SNode __thisNode__, String name) {
    ImportedModule__BehaviorDescriptor.createSubmoduleBySimpleName_id4O4oHuBgrqH(__thisNode__, name);
  }
}
