package PythonMPS.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ImportedModule_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IModule_BehaviorDescriptor {
  public SNode virtual_container_5549669319191144388(SNode __thisNode__) {
    return null;
  }
  public List<SNode> virtual_contents_5549669319191147593(SNode __thisNode__) {
    return null;
  }
  public String virtual_getFqName_1213877404258(SNode __thisNode__) {
    return null;
  }
  public String virtual_qualifiedName_5549669319191144399(SNode __thisNode__) {
    return null;
  }
  public List<SNode> virtual_subModules_5549669319191147617(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "PythonMPS.structure.ImportedModule";
  }

}
