package PythonMPS.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface IQNamedConcept_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
  public SNode virtual_container_5549669319191144388(SNode thisNode);
  public String virtual_qualifiedName_5549669319191144399(SNode thisNode);
}
