package PythonMPS.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Package_Behavior {
  public static void call_importContents_5549669319190172829(SNode __thisNode__) {
    Package__BehaviorDescriptor.importContents_id4O4oHuBdHit(__thisNode__);
  }
  public static String call_qualifiedName_5549669319190582895(SNode __thisNode__) {
    return Package__BehaviorDescriptor.qualifiedName_id4O4oHuBfhpJ(__thisNode__);
  }
  public static int call_nbOfLevel_5549669319190682782(SNode __thisNode__) {
    return Package__BehaviorDescriptor.nbOfLevel_id4O4oHuBfDMu(__thisNode__);
  }
  public static SNode call_getSubpackage_5549669319190717547(SNode __thisNode__, String name) {
    return Package__BehaviorDescriptor.getSubpackage_id4O4oHuBfMhF(__thisNode__, name);
  }
  public static SNode call_getSubpackageByQname_5549669319190908667(SNode __thisNode__, String qname) {
    return Package__BehaviorDescriptor.getSubpackageByQname_id4O4oHuBgwVV(__thisNode__, qname);
  }
  public static SNode call_getOrCreateSubpackageByQname_5549669319190714480(SNode __thisNode__, String name) {
    return Package__BehaviorDescriptor.getOrCreateSubpackageByQname_id4O4oHuBfLxK(__thisNode__, name);
  }
  public static SNode call_getOrCreateSubpackage_5549669319191072069(SNode __thisNode__, String name) {
    return Package__BehaviorDescriptor.getOrCreateSubpackage_id4O4oHuBh8P5(__thisNode__, name);
  }
  public static void call_createSubpackageByQname_5549669319190670441(SNode __thisNode__, String qname) {
    Package__BehaviorDescriptor.createSubpackageByQname_id4O4oHuBfALD(__thisNode__, qname);
  }
  public static void call_createSubpackage_5549669319190886061(SNode __thisNode__, String name) {
    Package__BehaviorDescriptor.createSubpackage_id4O4oHuBgrqH(__thisNode__, name);
  }
}
