package PythonRuntime.code;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;
import java.io.File;
import jetbrains.mps.project.PathMacros;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import PythonMPS.behavior.IQNamedConcept__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import PythonMPS.behavior.ImportedModule__BehaviorDescriptor;
import java.util.Comparator;

public class PythonModulesImporter {

  private List<String> runScript(String scriptName, List<String> params) {
    List<String> output = ListSequence.fromList(new LinkedList<String>());

    File pythonScriptsDir = new File(PathMacros.getInstance().getValue("python_scripts"));
    File script = new File(pythonScriptsDir.getPath() + File.separator + scriptName);

    // set up the command and parameter 
    String[] cmd = new String[2 + ListSequence.fromList(params).count()];
    cmd[0] = "python";
    cmd[1] = script.getAbsolutePath();
    for (int i = 0; i < ListSequence.fromList(params).count(); i++) {
      cmd[2 + i] = ListSequence.fromList(params).getElement(i);
    }

    // create runtime to execute external command 
    Runtime rt = Runtime.getRuntime();
    try {
      Process pr = rt.exec(cmd);
      pr.waitFor();

      BufferedReader bfr = new BufferedReader(new InputStreamReader(pr.getInputStream()));
      String line = "";
      while ((line = bfr.readLine()) != null) {
        ListSequence.fromList(output).addElement(line);
      }

      BufferedReader bfrError = new BufferedReader(new InputStreamReader(pr.getErrorStream()));
      String lineErrir = "";
      while ((lineErrir = bfrError.readLine()) != null) {
        // display each output line form python script 
        System.out.println(lineErrir);
      }

    } catch (IOException e) {
      System.out.println(e.getMessage());
    } catch (InterruptedException e) {
      System.out.println(e.getMessage());
    }
    return output;
  }

  private SNode parseParam(String paramStr) {
    SNode param = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74ed417L, "PythonMPS.structure.ImportedFunctionParam")));
    if (paramStr.startsWith("*")) {
      paramStr = paramStr.substring(1);
      SPropertyOperations.set(param, MetaAdapterFactory.getProperty(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74ed417L, 0x4d0462d7a74ed41aL, "varargs"), "" + (true));
    }
    SPropertyOperations.set(param, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), paramStr);
    return param;
  }

  public void importModuleContents(SNode pack) {
    for (String line : runScript("package_contents.py", ListSequence.fromListAndArray(new LinkedList<String>(), IQNamedConcept__BehaviorDescriptor.qualifiedName_id4O4oHuBhqvf.invoke(pack)))) {
      if (line.startsWith("class ")) {
        String className = line.split(" ")[1];
        SNode clazz = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74f7d33L, "PythonMPS.structure.ImportedClass")));
        SPropertyOperations.set(clazz, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), className);
        ListSequence.fromList(SLinkOperations.getChildren(pack, MetaAdapterFactory.getContainmentLink(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a73028c9L, 0x4d0462d7a736d428L, "contents"))).addElement(clazz);
      } else if (line.startsWith("value ")) {
        String valueName = line.split(" ")[1];
        SNode value = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74e3a7fL, "PythonMPS.structure.ImportedValue")));
        SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), valueName);
        ListSequence.fromList(SLinkOperations.getChildren(pack, MetaAdapterFactory.getContainmentLink(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a73028c9L, 0x4d0462d7a736d428L, "contents"))).addElement(value);
      } else if (line.startsWith("function ")) {
        String funcName = line.split(" ")[1];
        SNode fun = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74ecc98L, "PythonMPS.structure.ImportedFunction")));
        String[] parts = line.split(" ");
        for (int i = 2; i < parts.length; i++) {
          ListSequence.fromList(SLinkOperations.getChildren(fun, MetaAdapterFactory.getContainmentLink(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74ecc98L, 0x4d0462d7a74ed4b4L, "params"))).addElement(parseParam(parts[i]));
        }
        SPropertyOperations.set(fun, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), funcName);
        ListSequence.fromList(SLinkOperations.getChildren(pack, MetaAdapterFactory.getContainmentLink(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a73028c9L, 0x4d0462d7a736d428L, "contents"))).addElement(fun);
      } else if (line.startsWith("builtin_function ")) {
        String funcName = line.split(" ")[1];
        SNode fun = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74ecc98L, "PythonMPS.structure.ImportedFunction")));
        SPropertyOperations.set(fun, MetaAdapterFactory.getProperty(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74ecc98L, 0x4d0462d7a74ecc9bL, "builtin"), "" + (true));
        String[] parts = line.split(" ");
        for (int i = 2; i < parts.length; i++) {
          ListSequence.fromList(SLinkOperations.getChildren(fun, MetaAdapterFactory.getContainmentLink(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a74ecc98L, 0x4d0462d7a74ed4b4L, "params"))).addElement(parseParam(parts[i]));
        }
        SPropertyOperations.set(fun, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), funcName);
        ListSequence.fromList(SLinkOperations.getChildren(pack, MetaAdapterFactory.getContainmentLink(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a73028c9L, 0x4d0462d7a736d428L, "contents"))).addElement(fun);
      } else {
        System.out.println(line);
      }
    }

  }
  public void importSubModules(SNode pack) {
    System.out.println("Importing submodules of " + IQNamedConcept__BehaviorDescriptor.qualifiedName_id4O4oHuBhqvf.invoke(pack));
    for (String line : runScript("subpackages_lister.py", ListSequence.fromListAndArray(new LinkedList<String>(), IQNamedConcept__BehaviorDescriptor.qualifiedName_id4O4oHuBhqvf.invoke(pack)))) {
      ImportedModule__BehaviorDescriptor.createSubmoduleByQname_id4O4oHuBfALD.invoke(pack, ((line == null ? null : line.trim())));
    }
  }

  public void importModules(SNode packagesImporter) {
    System.out.println("importPackage: started");
    ListSequence.fromList(SLinkOperations.getChildren(packagesImporter, MetaAdapterFactory.getContainmentLink(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a72f9fbfL, 0x4d0462d7a73028ccL, "topLevelModules"))).clear();
    List<String> topPackages = runScript("packages_lister.py", ListSequence.fromList(new LinkedList<String>()));
    topPackages = ListSequence.fromList(topPackages).sort(new Comparator<String>() {
      public int compare(String a, String b) {
        return a.compareTo(b);
      }
    }, true).toListSequence();
    for (String line : topPackages) {
      SNode pack = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a73028c9L, "PythonMPS.structure.ImportedModule")));
      SPropertyOperations.set(pack, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), ((line == null ? null : line.trim())));
      ListSequence.fromList(SLinkOperations.getChildren(packagesImporter, MetaAdapterFactory.getContainmentLink(0x60430e8de6e24ceeL, 0x94b3c079312926d6L, 0x4d0462d7a72f9fbfL, 0x4d0462d7a73028ccL, "topLevelModules"))).addElement(pack);
    }
  }
}
